src/Entity/FraisForfait.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\FraisForfaitRepository")
 */
class FraisForfait
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $Libelle;

    /**
     * @ORM\Column(type="decimal", precision=5, scale=2)
     */
    private $Montant;

    
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLibelle(): ?string
    {
        return $this->Libelle;
    }

    public function setLibelle(string $Libelle): self
    {
        $this->Libelle = $Libelle;

        return $this;
    }

    public function getMontant(): ?string
    {
        return $this->Montant;
    }

    public function setMontant(string $Montant): self
    {
        $this->Montant = $Montant;

        return $this;
    }

    
}

src/Form/FraisforfaitType.php
<?php

namespace App\Form;

use App\Entity\FraisForfait;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\FormType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\ResetType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
class FraisforfaitType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('Libelle',TextType::class, array('label'=>'Libelle:','attr'=>array('class'=>'form-control', 'placeholder'=>'Libelle')))
            ->add('Montant',NumberType::class, array('label'=>'montant:','attr'=>array('class'=>'form-control', 'placeholder'=>'montant')))
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => FraisForfait::class,
        ]);
    }
}

src/Controller/FraisforfaitController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class FraisforfaitController extends AbstractController
{
    /**
     * @Route("/fraisforfait", name="fraisforfait")
     */
    public function index()
    {
        return $this->render('fraisforfait/index.html.twig', [
            'controller_name' => 'FraisforfaitController',
        ]);
    }
}

templates/fraisforfait/FFdeVisiteur.html.twig
{% extends "comptable/ménu.html.twig" %}
{% block body %}
    
<style type="text/css">
        
table {
  border-collapse: collapse;
  width: 100%;
}

th, td {
  text-align: left;
  padding: 8px;
}

tr:nth-child(even){background-color: #f2f2f2}

th {
  background-color:bisque;
  color:black;
}

</style>

  
<div name="droite" style="margin:auto; width:50%;">
    <div name="haut" style="margin: 2 2 2 2 ;height:20%;float:left;"><h1>Validation des Frais</h1></div>	
    <div name="bas" style="margin : 10 2 2 2;clear:left;background-color:EE8844;color:white;height:88%;">
            
    <form name="formValidFrais" method="post" action="enregValidFrais.php">    
   
        <div style="margin: 2 2 2 2 ;height:10%;float:center;">
        <h2>Frais au forfait </h2></div>
        <table style="color:black;" border="1">
            
            {% for unff in ligneff %} 
                     
            <tr><th>Etape</th><th>Km </th><th>Nuitée </th><th>Repas midi</th><th>Situation</th></tr>
                {#{ unff.getFraisforfait()}}
                {# if unff.getFraisforfait().getId()== 4 %#}
            <tr>

                <td>{% if unff.getFraisforfait().id==1 and unff.getFichefrais().id == unff.getFichefrais().id%}
                        {{unff.quantite  }}
                        
                    {% endif %}
                </td>
                {#% elseif unff.getligneff()== 3 %#}
                <td>{% if unff.getFraisforfait().id==2 and unff.getFichefrais().id == unff.getFichefrais().id%}
                        {{unff.quantite  }}
                    {% endif %}
                </td> 
                {#% elseif unff.getFraisforfait()== 1 %#}
                <td>{% if unff.getFraisforfait().id==3 and unff.getFichefrais().id == unff.getFichefrais().id%}
                        {{unff.quantite  }}
                    {% endif %}
                </td>
                {#% elseif unff.getFraisforfait()== 2 %#}
                <td>{% if unff.getFraisforfait().id==4 and unff.getFichefrais().id == unff.getFichefrais().id%}
                        {{unff.quantite  }}
                    {% endif %}
                </td>

                <td> 
                    <select size="3" name="situ">
                        <option value="E">Enregistré</option>
                        <option value="V">Validé</option>
                        <option value="R">Remboursé</option>
                    </select></td>
            </tr>
                    
                
                
            {% endfor %}

        </table>
                    
        
        <div style="margin: 2 2 2 2 ;height:10%;float:center;">
        <h2>Hors Forfait</h2></div>
            {% for lhf in horsforfait %}
            <table style="color:black;" border="1">
                
                <tr><th>Date</th><th>Libellé </th><th>Montant</th><th>Situation</th></tr>
                <tr><td>{{lhf.date|date('Y-m-d')}}</td>
                    <td>{{lhf.libelle}}</td> 
                    <td>{{lhf.montant}}</td>
                    <td> 
                        <select size="3" name="hfSitu1">
                            <option value="E">Enregistré</option>
                            <option value="V">Validé</option>
                            <option value="R">Remboursé</option>
                        </select></td>
                </tr>
            </table>
            {% endfor %}  
            
        <p>
            <div>Nb Justificatifs</div><input type="text" class="zone" size="4" name="hcMontant"/>		
        </p>
        
        </div>
            <p>
                <div>
                    <a href="#" ><button type="button" class="btn btn-warning">Valider</button> </a>
                    <a href="#"><button type="button" class="btn btn-warning">Annuler</button> </a>
                </div>
            </p>
    </form>
</div>

    
{% endblock %}

templates/fraisforfait/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello FraisforfaitController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ '/var/www/html/comptableGSB/src/Controller/FraisforfaitController.php'|file_link(0) }}">src/Controller/FraisforfaitController.php</a></code></li>
        <li>Your template at <code><a href="{{ '/var/www/html/comptableGSB/templates/fraisforfait/index.html.twig'|file_link(0) }}">templates/fraisforfait/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}